/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as MyPrsIndexRouteImport } from './routes/my-prs/index'
import { Route as OwnerRepoIndexRouteImport } from './routes/$owner/$repo/index'
import { Route as OwnerRepoPullsNumberHeaderRouteImport } from './routes/$owner/$repo/pulls/$number/_header'
import { Route as OwnerRepoPullsNumberHeaderFileChangesRouteImport } from './routes/$owner/$repo/pulls/$number/_header/file-changes'
import { Route as OwnerRepoPullsNumberHeaderConversationRouteImport } from './routes/$owner/$repo/pulls/$number/_header/conversation'

const LoginLazyRouteImport = createFileRoute('/login')()
const AboutLazyRouteImport = createFileRoute('/about')()
const IndexLazyRouteImport = createFileRoute('/')()

const LoginLazyRoute = LoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const AboutLazyRoute = AboutLazyRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const MyPrsIndexRoute = MyPrsIndexRouteImport.update({
  id: '/my-prs/',
  path: '/my-prs/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoIndexRoute = OwnerRepoIndexRouteImport.update({
  id: '/$owner/$repo/',
  path: '/$owner/$repo/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoPullsNumberHeaderRoute =
  OwnerRepoPullsNumberHeaderRouteImport.update({
    id: '/$owner/$repo/pulls/$number/_header',
    path: '/$owner/$repo/pulls/$number',
    getParentRoute: () => rootRouteImport,
  } as any)
const OwnerRepoPullsNumberHeaderFileChangesRoute =
  OwnerRepoPullsNumberHeaderFileChangesRouteImport.update({
    id: '/file-changes',
    path: '/file-changes',
    getParentRoute: () => OwnerRepoPullsNumberHeaderRoute,
  } as any)
const OwnerRepoPullsNumberHeaderConversationRoute =
  OwnerRepoPullsNumberHeaderConversationRouteImport.update({
    id: '/conversation',
    path: '/conversation',
    getParentRoute: () => OwnerRepoPullsNumberHeaderRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/login': typeof LoginLazyRoute
  '/my-prs/': typeof MyPrsIndexRoute
  '/$owner/$repo/': typeof OwnerRepoIndexRoute
  '/$owner/$repo/pulls/$number': typeof OwnerRepoPullsNumberHeaderRouteWithChildren
  '/$owner/$repo/pulls/$number/conversation': typeof OwnerRepoPullsNumberHeaderConversationRoute
  '/$owner/$repo/pulls/$number/file-changes': typeof OwnerRepoPullsNumberHeaderFileChangesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/login': typeof LoginLazyRoute
  '/my-prs': typeof MyPrsIndexRoute
  '/$owner/$repo': typeof OwnerRepoIndexRoute
  '/$owner/$repo/pulls/$number': typeof OwnerRepoPullsNumberHeaderRouteWithChildren
  '/$owner/$repo/pulls/$number/conversation': typeof OwnerRepoPullsNumberHeaderConversationRoute
  '/$owner/$repo/pulls/$number/file-changes': typeof OwnerRepoPullsNumberHeaderFileChangesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/login': typeof LoginLazyRoute
  '/my-prs/': typeof MyPrsIndexRoute
  '/$owner/$repo/': typeof OwnerRepoIndexRoute
  '/$owner/$repo/pulls/$number/_header': typeof OwnerRepoPullsNumberHeaderRouteWithChildren
  '/$owner/$repo/pulls/$number/_header/conversation': typeof OwnerRepoPullsNumberHeaderConversationRoute
  '/$owner/$repo/pulls/$number/_header/file-changes': typeof OwnerRepoPullsNumberHeaderFileChangesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/my-prs/'
    | '/$owner/$repo/'
    | '/$owner/$repo/pulls/$number'
    | '/$owner/$repo/pulls/$number/conversation'
    | '/$owner/$repo/pulls/$number/file-changes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/my-prs'
    | '/$owner/$repo'
    | '/$owner/$repo/pulls/$number'
    | '/$owner/$repo/pulls/$number/conversation'
    | '/$owner/$repo/pulls/$number/file-changes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/my-prs/'
    | '/$owner/$repo/'
    | '/$owner/$repo/pulls/$number/_header'
    | '/$owner/$repo/pulls/$number/_header/conversation'
    | '/$owner/$repo/pulls/$number/_header/file-changes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AboutLazyRoute: typeof AboutLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  MyPrsIndexRoute: typeof MyPrsIndexRoute
  OwnerRepoIndexRoute: typeof OwnerRepoIndexRoute
  OwnerRepoPullsNumberHeaderRoute: typeof OwnerRepoPullsNumberHeaderRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-prs/': {
      id: '/my-prs/'
      path: '/my-prs'
      fullPath: '/my-prs/'
      preLoaderRoute: typeof MyPrsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/': {
      id: '/$owner/$repo/'
      path: '/$owner/$repo'
      fullPath: '/$owner/$repo/'
      preLoaderRoute: typeof OwnerRepoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/pulls/$number/_header': {
      id: '/$owner/$repo/pulls/$number/_header'
      path: '/$owner/$repo/pulls/$number'
      fullPath: '/$owner/$repo/pulls/$number'
      preLoaderRoute: typeof OwnerRepoPullsNumberHeaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/pulls/$number/_header/file-changes': {
      id: '/$owner/$repo/pulls/$number/_header/file-changes'
      path: '/file-changes'
      fullPath: '/$owner/$repo/pulls/$number/file-changes'
      preLoaderRoute: typeof OwnerRepoPullsNumberHeaderFileChangesRouteImport
      parentRoute: typeof OwnerRepoPullsNumberHeaderRoute
    }
    '/$owner/$repo/pulls/$number/_header/conversation': {
      id: '/$owner/$repo/pulls/$number/_header/conversation'
      path: '/conversation'
      fullPath: '/$owner/$repo/pulls/$number/conversation'
      preLoaderRoute: typeof OwnerRepoPullsNumberHeaderConversationRouteImport
      parentRoute: typeof OwnerRepoPullsNumberHeaderRoute
    }
  }
}

interface OwnerRepoPullsNumberHeaderRouteChildren {
  OwnerRepoPullsNumberHeaderConversationRoute: typeof OwnerRepoPullsNumberHeaderConversationRoute
  OwnerRepoPullsNumberHeaderFileChangesRoute: typeof OwnerRepoPullsNumberHeaderFileChangesRoute
}

const OwnerRepoPullsNumberHeaderRouteChildren: OwnerRepoPullsNumberHeaderRouteChildren =
  {
    OwnerRepoPullsNumberHeaderConversationRoute:
      OwnerRepoPullsNumberHeaderConversationRoute,
    OwnerRepoPullsNumberHeaderFileChangesRoute:
      OwnerRepoPullsNumberHeaderFileChangesRoute,
  }

const OwnerRepoPullsNumberHeaderRouteWithChildren =
  OwnerRepoPullsNumberHeaderRoute._addFileChildren(
    OwnerRepoPullsNumberHeaderRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutLazyRoute: AboutLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  MyPrsIndexRoute: MyPrsIndexRoute,
  OwnerRepoIndexRoute: OwnerRepoIndexRoute,
  OwnerRepoPullsNumberHeaderRoute: OwnerRepoPullsNumberHeaderRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
