/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PullsIndexImport } from './routes/pulls/index'
import { Route as PullsOwnerRepoIndexImport } from './routes/pulls/$owner/$repo/index'
import { Route as PullsOwnerRepoNumberHeaderImport } from './routes/pulls/$owner/$repo/$number/_header'
import { Route as PullsOwnerRepoNumberHeaderFileChangesImport } from './routes/pulls/$owner/$repo/$number/_header/file-changes'
import { Route as PullsOwnerRepoNumberHeaderConversationImport } from './routes/pulls/$owner/$repo/$number/_header/conversation'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()
const PullsOwnerRepoNumberImport = createFileRoute(
  '/pulls/$owner/$repo/$number',
)()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const PullsIndexRoute = PullsIndexImport.update({
  id: '/pulls/',
  path: '/pulls/',
  getParentRoute: () => rootRoute,
} as any)

const PullsOwnerRepoNumberRoute = PullsOwnerRepoNumberImport.update({
  id: '/pulls/$owner/$repo/$number',
  path: '/pulls/$owner/$repo/$number',
  getParentRoute: () => rootRoute,
} as any)

const PullsOwnerRepoIndexRoute = PullsOwnerRepoIndexImport.update({
  id: '/pulls/$owner/$repo/',
  path: '/pulls/$owner/$repo/',
  getParentRoute: () => rootRoute,
} as any)

const PullsOwnerRepoNumberHeaderRoute = PullsOwnerRepoNumberHeaderImport.update(
  {
    id: '/_header',
    getParentRoute: () => PullsOwnerRepoNumberRoute,
  } as any,
)

const PullsOwnerRepoNumberHeaderFileChangesRoute =
  PullsOwnerRepoNumberHeaderFileChangesImport.update({
    id: '/file-changes',
    path: '/file-changes',
    getParentRoute: () => PullsOwnerRepoNumberHeaderRoute,
  } as any)

const PullsOwnerRepoNumberHeaderConversationRoute =
  PullsOwnerRepoNumberHeaderConversationImport.update({
    id: '/conversation',
    path: '/conversation',
    getParentRoute: () => PullsOwnerRepoNumberHeaderRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/pulls/': {
      id: '/pulls/'
      path: '/pulls'
      fullPath: '/pulls'
      preLoaderRoute: typeof PullsIndexImport
      parentRoute: typeof rootRoute
    }
    '/pulls/$owner/$repo/': {
      id: '/pulls/$owner/$repo/'
      path: '/pulls/$owner/$repo'
      fullPath: '/pulls/$owner/$repo'
      preLoaderRoute: typeof PullsOwnerRepoIndexImport
      parentRoute: typeof rootRoute
    }
    '/pulls/$owner/$repo/$number': {
      id: '/pulls/$owner/$repo/$number'
      path: '/pulls/$owner/$repo/$number'
      fullPath: '/pulls/$owner/$repo/$number'
      preLoaderRoute: typeof PullsOwnerRepoNumberImport
      parentRoute: typeof rootRoute
    }
    '/pulls/$owner/$repo/$number/_header': {
      id: '/pulls/$owner/$repo/$number/_header'
      path: '/pulls/$owner/$repo/$number'
      fullPath: '/pulls/$owner/$repo/$number'
      preLoaderRoute: typeof PullsOwnerRepoNumberHeaderImport
      parentRoute: typeof PullsOwnerRepoNumberRoute
    }
    '/pulls/$owner/$repo/$number/_header/conversation': {
      id: '/pulls/$owner/$repo/$number/_header/conversation'
      path: '/conversation'
      fullPath: '/pulls/$owner/$repo/$number/conversation'
      preLoaderRoute: typeof PullsOwnerRepoNumberHeaderConversationImport
      parentRoute: typeof PullsOwnerRepoNumberHeaderImport
    }
    '/pulls/$owner/$repo/$number/_header/file-changes': {
      id: '/pulls/$owner/$repo/$number/_header/file-changes'
      path: '/file-changes'
      fullPath: '/pulls/$owner/$repo/$number/file-changes'
      preLoaderRoute: typeof PullsOwnerRepoNumberHeaderFileChangesImport
      parentRoute: typeof PullsOwnerRepoNumberHeaderImport
    }
  }
}

// Create and export the route tree

interface PullsOwnerRepoNumberHeaderRouteChildren {
  PullsOwnerRepoNumberHeaderConversationRoute: typeof PullsOwnerRepoNumberHeaderConversationRoute
  PullsOwnerRepoNumberHeaderFileChangesRoute: typeof PullsOwnerRepoNumberHeaderFileChangesRoute
}

const PullsOwnerRepoNumberHeaderRouteChildren: PullsOwnerRepoNumberHeaderRouteChildren =
  {
    PullsOwnerRepoNumberHeaderConversationRoute:
      PullsOwnerRepoNumberHeaderConversationRoute,
    PullsOwnerRepoNumberHeaderFileChangesRoute:
      PullsOwnerRepoNumberHeaderFileChangesRoute,
  }

const PullsOwnerRepoNumberHeaderRouteWithChildren =
  PullsOwnerRepoNumberHeaderRoute._addFileChildren(
    PullsOwnerRepoNumberHeaderRouteChildren,
  )

interface PullsOwnerRepoNumberRouteChildren {
  PullsOwnerRepoNumberHeaderRoute: typeof PullsOwnerRepoNumberHeaderRouteWithChildren
}

const PullsOwnerRepoNumberRouteChildren: PullsOwnerRepoNumberRouteChildren = {
  PullsOwnerRepoNumberHeaderRoute: PullsOwnerRepoNumberHeaderRouteWithChildren,
}

const PullsOwnerRepoNumberRouteWithChildren =
  PullsOwnerRepoNumberRoute._addFileChildren(PullsOwnerRepoNumberRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/pulls': typeof PullsIndexRoute
  '/pulls/$owner/$repo': typeof PullsOwnerRepoIndexRoute
  '/pulls/$owner/$repo/$number': typeof PullsOwnerRepoNumberHeaderRouteWithChildren
  '/pulls/$owner/$repo/$number/conversation': typeof PullsOwnerRepoNumberHeaderConversationRoute
  '/pulls/$owner/$repo/$number/file-changes': typeof PullsOwnerRepoNumberHeaderFileChangesRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/pulls': typeof PullsIndexRoute
  '/pulls/$owner/$repo': typeof PullsOwnerRepoIndexRoute
  '/pulls/$owner/$repo/$number': typeof PullsOwnerRepoNumberHeaderRouteWithChildren
  '/pulls/$owner/$repo/$number/conversation': typeof PullsOwnerRepoNumberHeaderConversationRoute
  '/pulls/$owner/$repo/$number/file-changes': typeof PullsOwnerRepoNumberHeaderFileChangesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/pulls/': typeof PullsIndexRoute
  '/pulls/$owner/$repo/': typeof PullsOwnerRepoIndexRoute
  '/pulls/$owner/$repo/$number': typeof PullsOwnerRepoNumberRouteWithChildren
  '/pulls/$owner/$repo/$number/_header': typeof PullsOwnerRepoNumberHeaderRouteWithChildren
  '/pulls/$owner/$repo/$number/_header/conversation': typeof PullsOwnerRepoNumberHeaderConversationRoute
  '/pulls/$owner/$repo/$number/_header/file-changes': typeof PullsOwnerRepoNumberHeaderFileChangesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/pulls'
    | '/pulls/$owner/$repo'
    | '/pulls/$owner/$repo/$number'
    | '/pulls/$owner/$repo/$number/conversation'
    | '/pulls/$owner/$repo/$number/file-changes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/pulls'
    | '/pulls/$owner/$repo'
    | '/pulls/$owner/$repo/$number'
    | '/pulls/$owner/$repo/$number/conversation'
    | '/pulls/$owner/$repo/$number/file-changes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/pulls/'
    | '/pulls/$owner/$repo/'
    | '/pulls/$owner/$repo/$number'
    | '/pulls/$owner/$repo/$number/_header'
    | '/pulls/$owner/$repo/$number/_header/conversation'
    | '/pulls/$owner/$repo/$number/_header/file-changes'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AboutLazyRoute: typeof AboutLazyRoute
  PullsIndexRoute: typeof PullsIndexRoute
  PullsOwnerRepoIndexRoute: typeof PullsOwnerRepoIndexRoute
  PullsOwnerRepoNumberRoute: typeof PullsOwnerRepoNumberRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutLazyRoute: AboutLazyRoute,
  PullsIndexRoute: PullsIndexRoute,
  PullsOwnerRepoIndexRoute: PullsOwnerRepoIndexRoute,
  PullsOwnerRepoNumberRoute: PullsOwnerRepoNumberRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/pulls/",
        "/pulls/$owner/$repo/",
        "/pulls/$owner/$repo/$number"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/pulls/": {
      "filePath": "pulls/index.tsx"
    },
    "/pulls/$owner/$repo/": {
      "filePath": "pulls/$owner/$repo/index.tsx"
    },
    "/pulls/$owner/$repo/$number": {
      "filePath": "pulls/$owner/$repo/$number",
      "children": [
        "/pulls/$owner/$repo/$number/_header"
      ]
    },
    "/pulls/$owner/$repo/$number/_header": {
      "filePath": "pulls/$owner/$repo/$number/_header.tsx",
      "parent": "/pulls/$owner/$repo/$number",
      "children": [
        "/pulls/$owner/$repo/$number/_header/conversation",
        "/pulls/$owner/$repo/$number/_header/file-changes"
      ]
    },
    "/pulls/$owner/$repo/$number/_header/conversation": {
      "filePath": "pulls/$owner/$repo/$number/_header/conversation.tsx",
      "parent": "/pulls/$owner/$repo/$number/_header"
    },
    "/pulls/$owner/$repo/$number/_header/file-changes": {
      "filePath": "pulls/$owner/$repo/$number/_header/file-changes.tsx",
      "parent": "/pulls/$owner/$repo/$number/_header"
    }
  }
}
ROUTE_MANIFEST_END */
